export const langData = {
  tr: {
    // Nav
    navProject: "Proje",
    navTeam: "Ekip",
    navSponsor: "Sponsorluk",
    navContact: "İletişim",
    navJoin: "Takıma Katıl",

    // Hero
    heroTitle: "İTÜ TAYF: Yörüngedeki İmzamız",
    heroSubtitle: "İstanbul Teknik Üniversitesi Uçak ve Uzay Bilimleri Fakültesi bünyesinde, TEKNOFEST için uydu teknolojileri geliştiriyoruz.",
    heroBtnProject: "Projemizi Keşfedin",
    heroBtnSponsor: "Bize Destek Olun (Sponsorluk)",

    // Project
    projectTitle: "TEKNOFEST Model Uydu Projemiz",
    projectText: "İTÜ Tayf ekibi, havacılık ve uzay sektöründe özellikle haberleşme teknolojileri alanında kendini geliştirmeyi ve bu yönde ürünler üretmeyi vizyon olarak belirlemiştir. 2024–2025 döneminde Teknofest Model Uydu Yarışması’na hazırlanırken, gelecekte Amerika ve Avrupa’daki çeşitli model uydu yarışmalarına katılmayı hedeflemektedir. Ayrıca, üzerinde çalıştığı yenilikçi AR-GE projeleri ile sektörde öncü olmayı ve bu projeleri girişime dönüştürmeyi amaçlamaktadır.",
    galleryTitle: "Uydu Modelimiz",
    projectAchievementsTitle: "Başarılarımız",
    ach1: "2023 Teknofest Model Uydu: DR (Design Review) raporundan 96.5/100 puan.",
    ach2: "2022’de kuruldu; disiplinler arası ekip yapısı ve süreçler oluşturuldu.",
    ach3: "2024–2025’te uydumuzu önemli ölçüde geliştirdik; önceki deneyimlerden öğrenerek bu yıl daha güçlü bir katılım için hazırlandık.",
    projectGoalsTitle: "Hedeflerimiz",
    goal1: "2025–2026’ta ABD/Avrupa’daki CanSat ve benzeri model uydu yarışmalarına katılım.",
    goal2: "TEKNOFEST Model Uydu’da daha güçlü bir geri dönüş ve uçtan uca uçuşa hazır entegrasyon.",
    goal3: "Yeni AR-GE projelerini ticarileştirip girişime dönüştürmek (ör. haberleşme/electronics pod).",
    badgeFounded: "Kuruluş: 2022",
    badgeDRScorePrefix: "DR Skoru: ",
    tabGallery: "Galeri",
    tab3D: "3B Model",
    hintPan: "İpucu: Parmağınızla çevirin, iki parmakla yakınlaştırın.",
    projectTimelineTitle: "Proje Takvimi",
    timelineItem1Date: "23 Ocak",
    timelineItem1Desc: "Şartname Yayını",
    timelineItem2Date: "1 Mayıs",
    timelineItem2Desc: "Kritik Tasarım Raporu (KTR)",
    timelineItem3Date: "10 Mayıs",
    timelineItem3Desc: "Uçuşa Hazırlık Raporu (UHR)",
    timelineItem4Date: "20 Ağustos",
    timelineItem4Desc: "TEKNOFEST Yarışma Haftası",

    // Team
    teamTitle: "Disiplinlerarası Teknik Kadromuz",
    teamCard1Title: "Mekanik Ekibi",
    teamCard1Text: "Uydunun ana şasisini, yük taşıyıcı sistemlerini ve fırlatma ortamının zorlu koşullarına dayanacak yapısal bütünlüğü tasarlar ve üretir.",
    teamCard2Title: "Elektronik Ekibi",
    teamCard2Text: "Güç dağıtım kartları, telemetri sensörleri ve ana uçuş bilgisayarı dahil olmak üzere tüm aviyonik sistemlerin tasarımından ve entegrasyonundan sorumludur.",
    teamCard3Title: "Uçuş Yazılımı Ekibi",
    teamCard3Text: "Sensör verilerini işleyen, telemetri paketlerini oluşturan ve yer istasyonu komutlarını yürüten gömülü yazılımı geliştirir.",
    teamCard4Title: "Yer İstasyonu Ekibi",
    teamCard4Text: "Uydudan gelen verileri almak, işlemek ve komutları uydumuza iletmek için gerekli anten ve yazılım altyapısını kurar ve yönetir.",
    teamCard5Title: "Organizasyon & Tasarım Ekibi",
    teamCard5Text: "Proje yönetimini, lojistiği, kurumsal ilişkileri ve sponsorluk süreçlerini yürüterek teknik ekibin önünü açar.",

    // Sponsor
    sponsorIntroTitle: "Vizyonumuza Ortak Olun",
    sponsorIntroSubtitle: "Türkiye'nin Milli Teknoloji Hamlesi'ne katkıda bulunacak genç mühendislere yatırım yapın. Sektör liderleriyle iş birliği yapmaya ve geleceğin teknolojilerini birlikte geliştirmeye hazırız.",
    sponsorIntroBtn: "Sponsorluk Dosyasını İndir",
    sponsorTiersTitle: "Sponsorluk Paketleri",
    sponsorTierPlatinumTitle: "Platin",
    sponsorTierPlatinumBadge: "En Popüler",
    sponsorTierPlatinumBenefit1: "Logonuzun uydumuz üzerinde yer alması",
    sponsorTierPlatinumBenefit2: "Tüm sosyal medya ve basılı materyallerde ana sponsor olarak yer alma",
    sponsorTierPlatinumBenefit3: "Şirketinize özel tanıtım etkinlikleri ve atölyeler",
    sponsorTierPlatinumBenefit4: "İşe alım süreçlerinde öncelikli yetenek havuzuna erişim",
    sponsorTierGoldTitle: "Altın",
    sponsorTierGoldBenefit1: "Sosyal medya ve web sitesinde logonuzun yer alması",
    sponsorTierGoldBenefit2: "Tanıtım materyallerinde belirgin şekilde yer alma",
    sponsorTierGoldBenefit3: "Kariyer günlerinde stant açma önceliği",
    sponsorTierSilverTitle: "Gümüş",
    sponsorTierSilverBenefit1: "Web sitemizde 'Destekçilerimiz' bölümünde yer alma",
    sponsorTierSilverBenefit2: "Sosyal medyada toplu teşekkür paylaşımlarında yer alma",
    sponsorFinalCtaTitle: "İş Birliğine Hazır mısınız?",
    sponsorFinalCtaText: "Detaylı sponsorluk görüşmesi, özel paketler veya sorularınız için doğrudan bizimle iletişime geçebilirsiniz.",
    contactEmailAriaLabel: "E-posta ile ulaşın",

    // Launches
    launchesKicker: "Uzayı anlık takip ediyoruz",
    launchesTitle: "Yaklaşan Uzay Fırlatmaları",
    launchesLead: "Dünya genelindeki bazı planlı fırlatmalar (UTC+3, İstanbul saati).",
    launchesLiveTag: "Gerçek zamanlı veri akışı",
    launchesListTitle: "Yaklaşan fırlatmalar",
    launchesLoading: "Fırlatma bilgileri yükleniyor...",
    launchesEmpty: "Şu anda listelenecek planlı fırlatma bulunamadı.",
    launchesError: "Fırlatma bilgileri yüklenirken bir hata oluştu. Daha sonra tekrar deneyin.",
    launchesShowMore: "Daha Fazla Göster",
    launchesShowLess: "Daha Az Göster",
    launchesTimeLabel: "Fırlatma zamanı (İstanbul, UTC+3)",
    launchesOperatorLabel: "Operatör",
    launchesLocationLabel: "Konum",
    launchesMissionLabel: "Görev",
    launchesUnknownName: "Bilinmeyen Fırlatma",
    launchesUnknownOperator: "Bilinmeyen operatör",
    launchesUnknownLocation: "Bilinmeyen konum",
    launchesNoDate: "Tarih açıklanmadı",
    
    // APOD
    apodTitle: "NASA Günün Uzay Fotoğrafı",
    apodSource: "Kaynak: NASA Astronomy Picture of the Day (APOD)",
    apodDateLabel: "Tarih",
    apodLoading: "NASA'dan günün uzay fotoğrafı yükleniyor...",
    apodError: "NASA'dan fotoğraf alınırken bir hata oluştu.",
    apodNoImage: "Bugünkü APOD bir görüntü değil (video veya başka bir medya türü).",
    apodFallbackText: "NASA'dan görsel yüklenemedi.",

    // Join
    joinTitle: "Takıma Katıl",
    joinLead: "Her gezegen bir ekip: rolünü seç, yörüngeye katıl.",
    joinItem1: "Gerçek donanım üzerinde uçtan uca deneyim",
    joinItem2: "Yarışma standardında süreç ve dokümantasyon",
    joinItem3: "Atölye imkânı ve mentor desteği",
    joinItem4: "Sektörle erken tanışma ve referans",

    // Contact
    contactTitle: "İletişime Geçin",
    contactText: "Projemiz hakkında daha fazla bilgi almak veya iş birliği fırsatlarını görüşmek için bize ulaşın.",
    contactLead: "tayf.takimi@itu.edu.tr",
    contactSendEmail: "E-posta Gönder",
    contactLinkedInAriaLabel: "LinkedIn - İTÜ TAYF",
    contactInstagramAriaLabel: "Instagram - İTÜ TAYF",

    // Other
    menuAriaLabel: "Menü",
    logoAlt: "İTÜ TAYF Logosu",
    rocketAlt: "Roket fotoğrafı",
    footerCopyright: "© 2025 İTÜ TAYF Proje Takımı. Tüm hakları saklıdır.",
    metricsTest: "Uçuş/Yer testi",
    metricsAccess: "Yıllık erişim",
    metricsMembers: "Aktif üye",
    metricsPartners: "Sanayi ortağı",
    metricsHours: "Atolye saati / dönem",
    projectImageAlt1: "Uydu render – ön görünüm",
    projectImageAlt2: "Uydu render – detay",
    projectImageAlt3: "Uydu render – yanal görünüm",
    projectImageAlt4: "Uydu render – bileşen yakın plan",
    projectImageAlt5: "Uydu render – genel görünüm",
  },
  en: {
    // Nav
    navProject: "Project",
    navTeam: "Team",
    navSponsor: "Sponsorship",
    navContact: "Contact",
    navJoin: "Join the Team",

    // Hero
    heroTitle: "İTÜ TAYF: Our Signature in Orbit",
    heroSubtitle: "Developing advanced satellite technology for TEKNOFEST within the ITU Faculty of Aeronautics and Astronautics.",
    heroBtnProject: "Discover Our Project",
    heroBtnSponsor: "Support Us (Sponsorship)",

    // Project
    projectTitle: "Our TEKNOFEST Model Satellite Project",
    projectText: "ITU Tayf’s vision is to develop products in aerospace—especially in communications technologies. While preparing for the TEKNOFEST Model Satellite Competition in 2024–2025, we aim to participate in various model satellite competitions in the US and Europe. We also plan to lead with innovative R&D projects and turn them into ventures.",
    galleryTitle: "Our Satellite Model",
    projectAchievementsTitle: "Our Achievements",
    ach1: "TEKNOFEST 2023 Model Satellite: 96.5/100 in the Design Review (DR) report.",
    ach2: "Founded in 2022; built a cross-disciplinary team and processes.",
    ach3: "In 2024–2025 we significantly improved our satellite; leveraging past experience to compete much stronger this year.",
    projectGoalsTitle: "Our Goals",
    goal1: "Join US/EU CanSat and similar competitions in 2025–2026.",
    goal2: "A stronger return to TEKNOFEST with end-to-end, flight-ready integration.",
    goal3: "Commercialize new R&D projects (e.g., comms/electronics pod) into a startup.",
    badgeFounded: "Founded: 2022",
    badgeDRScorePrefix: "DR Score: ",
    tabGallery: "Gallery",
    tab3D: "3D Model",
    hintPan: "Tip: Drag to rotate, pinch to zoom.",
    projectTimelineTitle: "Project Timeline",
    timelineItem1Date: "January 23",
    timelineItem1Desc: "Release of Specifications",
    timelineItem2Date: "May 1",
    timelineItem2Desc: "Critical Design Report (CDR)",
    timelineItem3Date: "May 10",
    timelineItem3Desc: "Flight Readiness Report (FRR)",
    timelineItem4Date: "August 20",
    timelineItem4Desc: "TEKNOFEST Competition Week",

    // Team
    teamTitle: "Our Interdisciplinary Technical Team",
    teamCard1Title: "Mechanical Team",
    teamCard1Text: "Designs and manufactures the satellite's main chassis, payload carrying systems, and the structural integrity to withstand launch conditions.",
    teamCard2Title: "Electronics Team",
    teamCard2Text: "Responsible for the design and integration of all avionics, including power distribution boards, telemetry sensors, and the main flight computer.",
    teamCard3Title: "Flight Software Team",
    teamCard3Text: "Develops the embedded software that processes sensor data, creates telemetry packets, and executes ground station commands.",
    teamCard4Title: "Ground Station Team",
    teamCard4Text: "Builds and manages the antenna and software infrastructure necessary to receive and process data from our satellite and transmit commands.",
    teamCard5Title: "Organization & Design Team",
    teamCard5Text: "Manages project timelines, logistics, corporate relations, and sponsorship processes, clearing the path for the technical teams.",
    
    // Sponsor
    sponsorIntroTitle: "Partner With Our Vision",
    sponsorIntroSubtitle: "Invest in the young engineers who will contribute to Turkey's National Technology Initiative. We are ready to collaborate with industry leaders to develop future technologies.",
    sponsorIntroBtn: "Download Sponsorship Deck",
    sponsorTiersTitle: "Sponsorship Packages",
    sponsorTierPlatinumTitle: "Platinum",
    sponsorTierPlatinumBadge: "Most Popular",
    sponsorTierPlatinumBenefit1: "Your logo featured prominently on our satellite",
    sponsorTierPlatinumBenefit2: "Main sponsor recognition in all social media and print materials",
    sponsorTierPlatinumBenefit3: "Exclusive promotional events and workshops for your company",
    sponsorTierPlatinumBenefit4: "Priority access to our talent pool for recruitment",
    sponsorTierGoldTitle: "Gold",
    sponsorTierGoldBenefit1: "Logo placement on our social media and website",
    sponsorTierGoldBenefit2: "Prominent recognition in promotional materials",
    sponsorTierGoldBenefit3: "Priority booth placement at career days",
    sponsorTierSilverTitle: "Silver",
    sponsorTierSilverBenefit1: "Inclusion in the 'Our Supporters' section of our website",
    sponsorTierSilverBenefit2: "Mention in collective social media thank-you posts",
    sponsorFinalCtaTitle: "Ready to Collaborate?",
    sponsorFinalCtaText: "For detailed sponsorship discussions, custom packages, or any questions, you can reach us directly.",
    contactEmailAriaLabel: "Contact us via Email",


    // Launches
    launchesKicker: "Tracking space, in real-time",
    launchesTitle: "Upcoming Space Launches",
    launchesLead: "A selection of planned launches worldwide (in UTC+3, Istanbul time).",
    launchesLiveTag: "Live data feed",
    launchesListTitle: "Upcoming launches",
    launchesLoading: "Loading launch data...",
    launchesEmpty: "No scheduled launches to display at the moment.",
    launchesError: "An error occurred while loading launch data. Please try again later.",
    launchesShowMore: "Show More",
    launchesShowLess: "Show Less",
    launchesTimeLabel: "Launch time (Istanbul, UTC+3)",
    launchesOperatorLabel: "Operator",
    launchesLocationLabel: "Location",
    launchesMissionLabel: "Mission",
    launchesUnknownName: "Unknown Launch",
    launchesUnknownOperator: "Unknown operator",
    launchesUnknownLocation: "Unknown location",
    launchesNoDate: "Date not announced",
    
    // APOD
    apodTitle: "NASA Picture of the Day",
    apodSource: "Source: NASA Astronomy Picture of the Day (APOD)",
    apodDateLabel: "Date",
    apodLoading: "Loading NASA's Picture of the Day...",
    apodError: "An error occurred fetching the NASA picture.",
    apodNoImage: "Today's APOD is not an image (it may be a video).",
    apodFallbackText: "Could not load image from NASA.",

    // Join
    joinTitle: "Join the Team",
    joinLead: "Every planet is a team: choose your role, join the orbit.",
    joinItem1: "Hands-on, end-to-end hardware experience",
    joinItem2: "Competition-grade processes & documentation",
    joinItem3: "Workshop access and mentoring",
    joinItem4: "Early industry exposure and references",

    // Contact
    contactTitle: "Get In Touch",
    contactText: "Contact us to learn more about our project or to discuss partnership opportunities.",
    contactLead: "tayf.takimi@itu.edu.tr",
    contactSendEmail: "Send Email",
    contactLinkedInAriaLabel: "LinkedIn - ITU TAYF",
    contactInstagramAriaLabel: "Instagram - ITU TAYF",

    // Other
    menuAriaLabel: "Menu",
    logoAlt: "ITU TAYF Logo",
    rocketAlt: "Rocket photo",
    footerCopyright: "© 2025 ITU TAYF Project Team. All rights reserved.",
    metricsTest: "Flight/Ground tests",
    metricsAccess: "Annual reach",
    metricsMembers: "Active members",
    metricsPartners: "Industry partners",
    metricsHours: "Workshop hours / semester",
    projectImageAlt1: "Satellite render - front view",
    projectImageAlt2: "Satellite render - detail",
    projectImageAlt3: "Satellite render - side view",
    projectImageAlt4: "Satellite render - component closeup",
    projectImageAlt5: "Satellite render - overview",
  }
};